version: "2"
services:
  catalog-ms:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - catalog-db
    labels:
      io.rancher.scheduler.affinity:host_label: id=n1
  catalog-db:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "3303:3307"
    labels:
      io.rancher.scheduler.affinity:host_label: id=n1




