version: '2'
services:
  post-db:
    image: mongo
    ports:
    - 3306:27017/tcp
    command:
    - --replSet
    - rs0
    - --bind_ip
    - 0.0.0.0
  post-ms:
    image: criscapunal/post-be:7.0
    ports:
    - 3002:3000/tcp





