version: "2"
services:
  post-db:
    image: mongo
    ports:
      - "3306:27017"
    labels:
      io.rancher.scheduler.affinity:host_label: id=n1
  post-ms:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - post-db
    labels:
      io.rancher.scheduler.affinity:host_label: id=n1



